### PR TITLE
Add extra info about dnsmasq with DNSSEC

### PR DESCRIPTION
**Pull request by aspyatkin**
I have added a tip on how to build `dnsmasq` with DNSSEC support along with necessary configuration options.

### CODE REVIEW

**Comment by dnwe** [comment]
👍🏼

Might be a good idea to reference https://www.iana.org/dnssec/files as the source for the root trust anchor

Also, unless there's a good reason why you wouldn't always want to enable this, I would remove the "..you might want to enable..." comment and just make with-dnssec the default brew cmd and config settings

**Comment by aspyatkin** [comment]
Sorry for such a delay. I made the corrections @dnwe had proposed.

**Comment by drduh** [comment]
Let me read up a bit on DNSSEC first. I admit to not knowing much about it, nor how it works in practice.

**Comment by TraderStf** [comment]
http://dnssec-debugger.verisignlabs.com/#

**Comment by drduh** [comment]
Okay. Just add a line above the install instructions to explain, in a few words, what DNSSEC is and where to read more about it. Maybe add a link to http://www.dnssec-failed.org/ to validate it's working.

**Comment by aspyatkin** [comment]
@drduh I've added:
1. An explanation of what DNSSEC is;
2. Links to [dnssec.net](http://www.dnssec.net) and root-zone anchors;
3. Tips on how to test DNSSEC validation (one with properly signed zone, another with improperly signed zone).

I tried to keep the description short, however DNS security is a big topic and I believe it can't be explained in a few words. There might be some language mistakes, as I'm not a fluent English speaker.

**Comment by drduh** [comment]
Nice one. Thanks very much!

**Pull request merged**
