### PR TITLE
Add note about Cloak's overcloak feature

### PR DESCRIPTION
**Pull request by wsargent**

### CODE REVIEW

**Comment by drduh** [comment]
I'm sure Cloak and Overcloak are fine, but this page reads like a marketing brochure, not a technical manual. Maybe reference to a VPN service review website, or creating our own comparison table, would be preferable.

**Comment by wsargent** [comment]
Would http://thesweetsetup.com/how-to-enable-overcloak-for-extra-security-with-cloak-for-mac/ be better?

**Comment by asvc** [comment]
What a bright idea to route all traffic traffic via the US based company. 

> Cloak is owned and operated by Cloak Holdings LLC, a legal entity which is headquartered in Dallas, TX, USA. We are subject to federal, state, and local laws and we will absolutely uphold them.

and my favorite part:

> When you use Cloak to secure your connection, we collect:
> 
>     The number of bytes you've sent and received
>     The amount of time you've been connected
>     The IP address you're connected from
>     The assigned (virtual) IP address on our VPN network
>     The source port of each outgoing connection with start and end times

**Comment by drduh** [comment]
On the one hand, even US-based VPN providers offer a useful thing: encryption to protect against a local eavesdropper. On the other, I can see how a nefarious panopticon could leverage VPN services to spy on or hack many unsuspecting victims, too.

This dilemma has come up before and it's why I've been hesitant to recommend any particular service. What do others think of another guide to set up one's own VPN? Or perhaps we can reference an existing system like https://github.com/jlund/streisand?

I'm interested in a community discussion on this topic.

**Comment by rawtaz** [comment]
There are other sites that inform about and compare services like VPN providers. The scope of this guide should be to inform about their (VPNs) existence, why/when they are important‎ to use, and possibly point to further resources. But it shouldnt be a comparison or point out specific services when there's this many of them.Streisand is different, as you can run it yourself and theres arguably few of that type of and complete software. So i think it's fine to mention‎ as it's more of a key player than one specific VPN service (unless there's something really unique with that service).So in short, it's fine to point to unique/key software, but when‎ the question is about something there's a ton of out there, the guide should be more neutral and generic/restrictive.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Från: drduhSkickat: lördagen den 17:e september 2016 16:48Till: drduh/OS-X-Security-and-Privacy-GuideSvara till: drduh/OS-X-Security-and-Privacy-GuideÄmne: Re: [drduh/OS-X-Security-and-Privacy-Guide] Add note about Cloak's overcloak feature (#134)On the one hand, even US-based VPN providers offer a useful thing: encryption to protect against a local eavesdropper. On the other, I can see how a nefarious panopticon could leverage VPN services to spy on or hack many unsuspecting victims, too.

This dilemma has come up before and it's why I've been hesitant to recommend any particular service. What do others think of another guide to set up one's own VPN? Or perhaps we can reference an existing system like https://github.com/jlund/streisand?

I'm interested in a community discussion on this topic.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/drduh/OS-X-Security-and-Privacy-Guide","title":"drduh/OS-X-Security-and-Privacy-Guide","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/drduh/OS-X-Security-and-Privacy-Guide"}},"updates":{"snippets":[{"icon":"PERSON","message":"@drduh in #134: On the one hand, even US-based VPN providers offer a useful thing: encryption to protect against a local eavesdropper. On the other, I can see how a nefarious panopticon could leverage VPN services to spy on or hack many unsuspecting victims, too.\r\n\r\nThis dilemma has come up before and it's why I've been hesitant to recommend any particular service. What do others think of another guide to set up one's own VPN? Or perhaps we can reference an existing system like https://github.com/jlund/streisand?\r\n\r\nI'm interested in a community discussion on this topic."}],"action":{"name":"View Pull Request","url":"https://github.com/drduh/OS-X-Security-and-Privacy-Guide/pull/134#issuecomment-247777188"}}}

**Comment by mdwod** [comment]
I agree with @rawtaz, I would assume that the guide shows informations about VPNs but leaves the comparison to others, since it takes **a lot** of work to explain all the details. As a first-step it could show a reference to a comparison of VPNs. 

I found [www.thatoneprivacysite.net/](https://thatoneprivacysite.net/vpn-comparison-chart/) that lists a lot of services and compares them and even explains what each section means.

**Comment by TraderStf** [comment]
I have another post about VPN.

The tasks to list them with their features is huge, I gave up, one of the reason is that some important criteria can't be verified: anonymity, logs, policy...
Except these, I suppose most usual users are looking for the same: speed, accessibility and reliability.

Just for the speed, from-to and the time of the day are different for everyone.
I came to the conclusion, trying for one month with your usual activities is the only valid test.

Few points to remind when selecting a vpn:
- email authorized (port 25...) very annoying when it's forbidden to avoid spammers...
- app available specially on macos/ios, or must use a third party crappy utility or expansive app
- dnsr locked or editable
- can define manually VPN in Apple - Network Prefs
- ip6 support

Few links discovered lately:

https://www.strongswan.org
OpenSource IPsec-based VPN Solution

http://www.vpnlist.net	
http://www.vpnsp.com/vpn-services.html

Good ~unbiased reviews:
https://vpnreviewer.com/
https://www.bestvpn.com/

They are probably paying attention to anonymity as they are copying stuff:
https://torrentfreak.com/vpn-anonymous-review-160220/
https://torrentfreak.com/anonymous-vpn-service-provider-review-2015-150228/

**Comment by wsargent** [comment]
> What a bright idea to route all traffic traffic via the US based company.

Nation state or VPN surveillance is not a part of my threat model -- I'm more concerned about the hak5 pineapple that's quietly sniffing traffic in the coffee shop.  Anything that routes data through VPN and blocks data from being transmitted over VPN is good in my book.  

I don't care whether it's Cloak or you're doing something fancy with IceFloor or Viscosity -- the point is that it provides a useful feature.

I absolutely don't want, nor care about, a discussion about "anonymity" in VPNs, or even anonymity in general.   You want anonymity, use Tor -- and even then you'll have problems because you'll eventually be traced by matching dirty entrance and exit nodes.  Anonymity is not what VPNs do, and it's a bullshit discussion.

**Comment by wsargent** [comment]
> I'm interested in a community discussion on this topic.

I am not.  Please either merge the PR or close it, either way I have better things to read.

**Comment by TraderStf** [comment]
https://www.getcloak.com/about/overcloak/
I don't want to argue, I don't know what's really going during the time VPN is fully active.

But is it not already blocked if you set:
- all traffic through the vpn
- and don't connect automatically to unknown/new WIFI in macos network settings
?

Thanks.

**Comment by TraderStf** [comment]
FYI, far from perfect, leaks must certainly occur but this little app at least reduces the time the vpn is off. some vpn are so bad, either cmd-q (so close to cmd-w etc) quits without warning or/and even continue to show you are under the vpn...

[VPN Monitor](http://vpnmonitor.eu)

On TF, an 'activist' VPN provider was explaining ~ an effective kill-switch is impossible/useless, those who say so are lying/ignorant.

I agree with @wsargent I am concerned about security, avoid ads, kids and others naughty. For 1984-anonymity... stop dreaming.

**Comment by drduh** [comment]
I prefer not endorse Cloak nor other commercial VPN providers at this time. Discussion can be had in a new issue, then.

**Pull request closed without merging**
